import numpy as np
import stim
from pymatching import Matching


# 1. Load the syndrome samples and logical labels generated by Stim
def load_samples():
    # Each row = one shot, each column = one detector (syndrome bit)
    det_path = "stim_files/data/detector_samples.csv"
    log_path = "stim_files/data/logical_labels.csv"

    detector_samples = np.loadtxt(det_path, delimiter=",", dtype=np.uint8)
    logical_labels = np.loadtxt(log_path, delimiter=",", dtype=np.uint8)

    # Ensure both arrays are 2D for consistent shape handling
    if detector_samples.ndim == 1:
        detector_samples = detector_samples.reshape(1, -1)
    if logical_labels.ndim == 1:
        logical_labels = logical_labels.reshape(-1, 1)

    print("detector_samples shape:", detector_samples.shape)
    print("logical_labels shape :", logical_labels.shape)
    return detector_samples, logical_labels


# 2. Rebuild the identical Stim circuit and construct a PyMatching decoder
def build_matching(distance=3, rounds=5, p=1e-3):
    print("Rebuilding Stim circuit with the SAME parameters used during data generation...")

    # Recreate the exact Stim circuit used to produce the dataset
    circ = stim.Circuit.generated(
        "surface_code:rotated_memory_z",
        distance=distance,
        rounds=rounds,
        after_clifford_depolarization=p,
        before_round_data_depolarization=p,
        before_measure_flip_probability=p,
        after_reset_flip_probability=p,
    )

    # Extract the Detector Error Model (DEM) from the circuit
    model = circ.detector_error_model(decompose_errors=True)

    print("Building PyMatching decoder from DEM...")
    matching = Matching.from_detector_error_model(model)

    print("num_detectors:", matching.num_detectors)
    print("num_nodes    :", matching.num_nodes)
    print("num_edges    :", matching.num_edges)

    return matching


# 3. Decode all shots using PyMatching and compute the logical error rate (LER)
def evaluate_decoder(matching, detector_samples, logical_labels):
    print("Decoding with PyMatching...")

    # Decode the full batch at once
    # Output shape: (num_shots, num_logicals)
    predicted_logicals = matching.decode_batch(detector_samples)

    # Ensure output is 2D
    if predicted_logicals.ndim == 1:
        predicted_logicals = predicted_logicals.reshape(-1, 1)

    print("predicted_logicals shape:", predicted_logicals.shape)

    # Logical error occurs if ANY logical output is incorrect for that shot
    errors_per_shot = np.any(predicted_logicals != logical_labels, axis=1)

    num_errors = np.sum(errors_per_shot)
    num_shots = detector_samples.shape[0]
    ler = num_errors / num_shots

    print(f"Total shots        : {num_shots}")
    print(f"Decoding failures  : {num_errors}")
    print(f"Logical error rate : {ler:.4e}")

    return ler


# Main execution
if __name__ == "__main__":
    dets, logs = load_samples()

    # Must match the parameters used in the original gen_dem() function
    matching = build_matching(distance=3, rounds=5, p=1e-3)
    
    evaluate_decoder(matching, dets, logs)
